### ISSUE TITLE
where is the download link

### ISSUE THREAD

**Issue by luccawashere** [Manu098vm/Tera-Finder#11]
where do i download this please and thank you

**Comment by Manu098vm** [comment]
A proper Release page with download links will be done once the program will be stable enough to be released. If you want to try the dev build:
- Log to a github account
- Click on "Actions" from the main Repository
- Click on the latest commit
- Scroll down to the "Artifact" section
- Click on the Tera-Finder link

**Comment by Legarad** [comment]
> A proper Release page with download links will be done once the program will be stable enough to be released. If you want to try the dev build:
> 
> * Log to a github account
> * Click on "Actions" from the main Repository
> * Click on the latest commit
> * Scroll down to the "Artifact" section
> * Click on the Tera-Finder link

It is not possible to download it that way.
