### ISSUE TITLE
No feature to extract pokenews from save file, just import

### ISSUE THREAD

**Issue by realquantumsource** [Manu098vm/Tera-Finder#12]
love the app/tools/plugins and progress so far, just wondering if there is plans to add a feature to extract poke news (event raids) from save file.

**Comment by Manu098vm** [comment]
Extracting the event files is not something that the average user would do. I added that feature in SVSaveBlockDecryptor on my Research repository if you want to take a look. 
https://github.com/Manu098vm/SVResearches

The feature won't be implemented in Tera Finder.
