### ISSUE TITLE
About translation

### ISSUE THREAD

**Issue by ppllouf** [Manu098vm/Tera-Finder#17]
Will you add language files like those PKHeX has to your plugins?

**Comment by Manu098vm** [comment]
I noticed your translation efforts for my and other plugins, it's very appreciated :)

If you're willing to pull request your translation to the main branch, then yeah I see no reason not to.

I will set up external files for translations later or tomorrow. Thank you again for your interest in the projects.

**Comment by ppllouf** [comment]
I will contribute to the translation of this plugin in Chinese ;)
