### ISSUE TITLE
Event pokemon get ?

### ISSUE THREAD

**Issue by Dalk2ness** [Manu098vm/Tera-Finder#24]
When event pokemon get ? on that, Need to update or not?
If not, How can i do something to get ืnew event data??

**Comment by Manu098vm** [comment]
I could not understand any of your questions. Please take a bit of time to rephrase. If you don't know english, please use a translator accordingly.

If this is related to the new Garchomp/Sylveon event, a fix for its handling is already planned. Please wait patiently. It will be pushed during this weekend.

**Comment by Dalk2ness** [comment]
OK, get it
only need to update for fixed it.
thanks
