### ISSUE TITLE
Poké Portal Event #11 - Garchomp and Sylveon Spotlight

### ISSUE THREAD

**Issue by GlacierWolf259** [Manu098vm/Tera-Finder#25]
So I'm trying the newest build of Tera Finder for this new Raid Event in Violet, but I'm only seeing Sylveon in the list despite there being both Sylveon and Garchomp in both versions.

**Comment by Manu098vm** [comment]
handled in https://github.com/Manu098vm/Tera-Finder/commit/e52bd23c6903622074c36f3ffa68a46c5c68264c
