### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by ewashington0630** [Manu098vm/Tera-Finder#3]
is the setup still the same way 
![image](https://user-images.githubusercontent.com/59975948/208269486-00a5e3f0-e7b3-4fb6-a91e-7a921ca8bbc2.png)
i got folder in the plugins folder

**Comment by Manu098vm** [comment]
Yes the setup is still the same. 
Be sure to download the latest commit from Github Actions (https://github.com/Manu098vm/Tera-Finder/actions), build PKHeX latest commit and double check to launch the PKHeX .Net 6 version. If it does not work try changing the plugin load method in PKHeX -> Settings -> Startup -> PluginLoadMethod.
Or just use the launcher instead. The launcher is included in the Github action build.
