### ISSUE TITLE
Terra Raid Remote Connect to switch

### ISSUE THREAD

**Issue by Leusele** [Manu098vm/Tera-Finder#36]
Hi, well do i get it right that i have to Play on my Emunand an Switch while using this?
And if yes, is there a way to host this raids online? Because of the "!dont wo online with Emunand" Rule?

Sorry if this might be a noob question, i just dont want to risk something.
Ty for your grate work!

**Comment by Manu098vm** [comment]
This is not intended to be used on EmuNand at all. 

SysNand CFW is what you want to use to host raids online. Atmosphere itself and Sysbot-base are not responsible for any ban so far. Piracy is. Don't do Piracy in your nand. Don't do cheat codes while online.

**Comment by Leusele** [comment]
well sure, no Piracy on my nand.
So i can use this tool without having ha hacked switch, cause i just need my sysnand?

**Comment by Manu098vm** [comment]
No, you need CFW on SysNand. An hacked unit is required.
