### ISSUE TITLE
Got error when try to build

### ISSUE THREAD

**Issue by Dalk2ness** [Manu098vm/Tera-Finder#38]
got this error when i try to build last update

![image](https://user-images.githubusercontent.com/10178164/230950348-c5605d49-dbe6-47c5-b14a-cd325626eb15.png)

**Comment by Manu098vm** [comment]
It seems that I can not replicate the issue. 
Try by deleting the `bin` and `obj` folders. Click on `Build` -> `Clean Solution` and then `Build` -> `Build Solution`.
If it doesn't work, download the repository in a new, clean directory and try again from there.

**Comment by Dalk2ness** [comment]
Thanks u for helping me to fixed ^^
