### ISSUE TITLE
Error on Raid Viewer/Editor

### ISSUE THREAD

**Issue by joshuacode751** [Manu098vm/Tera-Finder#4]
Happens on latest PKHex master
![image](https://user-images.githubusercontent.com/32216817/208298871-d32ca86e-0d7c-489d-a69f-b18cd947e43d.png)

**Comment by Manu098vm** [comment]
Yeah latest PKHeX commit changed sprites handling: https://github.com/kwsch/PKHeX/commit/f5ea2509752053ee3896bd7ae916c34fac6e8fd3#diff-ed43f5e9a140f0657c13ed4abc972991581ff7193e7cc409e96a10e26f99bce0L62

I have to change some stuff to make it work again with latest commit, i will work on it soon. Thanks for the report :)

**Comment by Manu098vm** [comment]
Should be solved https://github.com/Manu098vm/Tera-Finder/commit/5b45bc0a538bea6ecd7386d440fa49909fe3c2e4 :)
