### ISSUE TITLE
Language Display

### ISSUE THREAD

**Issue by nlqhs** [Manu098vm/Tera-Finder#40]
I was wondering if it's possible to display in English for other languages save.

**Comment by Manu098vm** [comment]
I have no plans to change the behaviour of the translation feature. You can eventually use Tera Finder as a [PKHeX plugin](https://github.com/Manu098vm/Tera-Finder/wiki/PKHeX-Plugin). The plugin uses the PKHeX set language instead of the save file language.

**Comment by Manu098vm** [comment]
You need to add all the DLLs in the plugins zip, not only TeraFinder.dll

**Comment by nlqhs** [comment]
ah it appears. thank you
