### ISSUE TITLE
[2.3.1] Connect to Remote Device- "No Remote Connection"

### ISSUE THREAD

**Issue by TestHelpPkmn** [Manu098vm/Tera-Finder#47]
I keep getting "No Remote Connection" error message when trying to use the "Connect to remote Device" feature.

However this was not an issue back in 2.2.0 but it is on 2.3.0

I am using the USB option rather than the Wifi connection.

**Comment by Manu098vm** [comment]
Solved in https://github.com/Manu098vm/Tera-Finder/commit/826fb8a1ac6e2666c7d4e36375eb60ffdf07a132
