### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by MicheleBiena** [Manu098vm/Tera-Finder#5]
Hi, would it be possible to add a reward filter on the raid calculator, or maybe is it already planned? I know that there's a feature in Raid Crawler that let's you check the raid rewards beforehand, so maybe it could be ported here.

**Comment by Manu098vm** [comment]
Hey thanks for your suggestion :)
The feature is planned and the skeleton for the rewards item structures has already been added. 
Idk when it will be completed, but it will, eventually.

**Comment by Manu098vm** [comment]
Reward calculator has been added in https://github.com/Manu098vm/Tera-Finder/commit/8d06371f7687c447612beb142ada327f88725c2f :)
