### ISSUE TITLE
Cannot be used continuously multiple times

### ISSUE THREAD

**Issue by ppllouf** [Manu098vm/Tera-Finder#51]
Thank you for merge new feature into the main branch.

The Shinify method you redesigned is excellent, but we found that it can only be run once and cannot be used continuously for the multiple time.

How does your code work using the next shiny seed?

Please design a method that can use this function multiple times. Thank you:)

**Comment by Manu098vm** [comment]
The method is intended to make all the raids as shiny raids. If a raid is already shiny, the method skips its shinyfication, since... it's already shiny.

**Comment by Manu098vm** [comment]
There are two options, one makes shiny random encounters, one keeps the current encounter for each raid. If users want to keep their known raids they can use the second option. 
If there's only a bunch of raids that the user want to edit, they can manually calculate the raid they want.
The goal of the methods is to get shiny raids, not an expected encounter. Again, if they want an expected encounter of their likings they can manually calculate a raid and set it to the editor.

Unless I'm missing / misunderstanding what you're saying, which is a possiblity. I don't see constantly random rerolls to be that useful to be honest, if you can provide some usecases I can eventually edit the methods.

**Comment by ppllouf** [comment]
Thank you for your reply. It reminds me of a new feature that I will try to add
