### ISSUE TITLE
Tera Raid Locations

### ISSUE THREAD

**Issue by LegoFigure11** [Manu098vm/Tera-Finder#59]
Per RaidCrawler [635061f](https://github.com/LegoFigure11/RaidCrawler/commit/635061fb4d3aa49bc5504d83e75cce7976bd038f), the tera raid location JSONs are now fully documented.
Additionally, there's no longer any need to display multiple possible locations for any given raid - the lookup uses the field that was previously thought to be `DisplayType` to find which location to use if there is more than one. Per the renamed fields in the [latest PKHeX commit](https://github.com/kwsch/PKHeX/commit/b4b72a8fda0dd646b532c8ba55f5094d53a0b6a1) and RaidCrawler's JSONs derived from the dump and revised to correct the missing locations, the exact coordinates for a den can be found under `LocationListFromJSON[$"{raid.AreaID}-{raid.LotteryGroup}-{raid.SpawnPointID}"]`.

**Comment by Manu098vm** [comment]
Thank you, much appreciated. How were the missing locations found? Checked manually?

**Comment by LegoFigure11** [comment]
Yup, Anubis and I went through and matched them up

**Comment by Manu098vm** [comment]
Fixed in https://github.com/Manu098vm/Tera-Finder/commit/52bd33f15746fa1dde33695218cd93ec95981827, thanks again :)
