### ISSUE TITLE
Some Kitakami raid den locations are off the map

### ISSUE THREAD

**Issue by observeroftime01** [Manu098vm/Tera-Finder#60]
Using PKHeX 2023.09.25
Using Tera-Finder compiled at commit 9ef53a8 using PKHeX.Core 2023.09.25 

Basically what the title states. Some of the raid den locations displayed are in inaccessible areas, or straight up not on the map. I have not yet checked to see if the other raid den locations are accurately displayed. Editing the raids however does appear to work properly. 

<details>
  <summary>Click for images showing the issue</summary>

![image](https://github.com/Manu098vm/Tera-Finder/assets/57168924/6974e752-ce7d-4acb-b0e5-0cc487f8e8b8)

![image](https://github.com/Manu098vm/Tera-Finder/assets/57168924/225b4da5-dd9d-4944-baa4-88aae7e2da68)

![image](https://github.com/Manu098vm/Tera-Finder/assets/57168924/561ce998-b632-4ee1-9718-91da80d6efd1)

![image](https://github.com/Manu098vm/Tera-Finder/assets/57168924/fe6e2a37-f15a-414b-b361-79906348ea57)

</details>

I'm not sure if this is still a work-in-progress, but I figure I let someone know sooner rather than later. If I can provide any additional details I would be happy to do so. Thank you for your time and hard work.

**Comment by Manu098vm** [comment]
Fixed in https://github.com/Manu098vm/Tera-Finder/commit/52bd33f15746fa1dde33695218cd93ec95981827 :)
